Aiven-Open/encrypted-repository-opensearch

- build.gradle
Bump up OpenSearchVersion to 1.3.2
> Bump up OpensearchVersion to 1.3.2

- src/main/java/org/opensearch/repository/encrypted/EncryptedBlobContainer.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedBlobStore.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepository.java
- src/main/java/org/opensearch/repository/encrypted/security/CryptoIO.java
- src/main/plugin-metadata/plugin-security.policy
- src/test/java/org/opensearch/repository/encrypted/security/CryptoIOTests.java
Changes:
- Fixed calculation of final encrypted stream, since we do not use padding for encryption
- Fixed issue https://github.com/aiven/encrypted-repository-opensearch/issues/21
- Added missing permissions for BouncyCastle
> Bugs fixing

- README.md
> Add version 2.0.0.0 to README

- build.gradle
Bump up OpenSearch to version 2.0.1
> Bump up OpenSearch to version 2.0.1

- src/main/java/org/opensearch/repository/encrypted/security/CryptoIO.java
Added BufferedInputStream so underlying
cloud clients could use mark/reset functionality for re-try.
> Use BufferedInputStream together with CipherInputStream

- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositorySettings.java
> Fix registration fo security providers

- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositoryPlugin.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositorySettings.java
Changes:
- Register BouncyCastle in plugin class
- Deprecate `encrypted.security_provider` settings
> Change the way how BC registered in the plugin

- build.gradle
Bump up OpenSearch to version 2.1.0
P.S: this is my first contribution don't hesitate to tell me if other requirements are needed for this to be merged.
> Bump up OpenSearch to version 2.1.0

- build.gradle
Bumped up OpenSearch to version 2.2.0
> Bump up OpenSearch to version 2.2.0

- build.gradle
Bumped up OpenSearch to version 2.2.1
> Bump up OpenSearch 2.2.1

- build.gradle
Bump up OpenSearch to version 2.5.0
> Bump up OpenSearch to version 2.5.0

- build.gradle
This reverts commit ea5c6b874d8833a9f4e00582268e9e34f5a868ff.
> Revert "Bump up OpenSearch to version 2.5.0"

- build.gradle
> Bump up OpenSearech 2.5

- build.gradle
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepository.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositoryPlugin.java
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositoryTests.java
Bump OpenSearch to version 2.7
> Bump OpenSearch to version 2.7

- src/main/java/org/opensearch/repository/encrypted/security/EncryptionDataSerializer.java
fix permission check during snapshot restoration
> fix permission check

- build.gradle
- checkstyle/checkstyle.xml
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/org/opensearch/repository/encrypted/EncryptedBlobContainer.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedBlobStore.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepository.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositoryPlugin.java
- src/main/java/org/opensearch/repository/encrypted/EncryptedRepositorySettings.java
- src/main/java/org/opensearch/repository/encrypted/Permissions.java
- src/main/java/org/opensearch/repository/encrypted/security/CryptoIO.java
- src/main/java/org/opensearch/repository/encrypted/security/Decryptor.java
- src/main/java/org/opensearch/repository/encrypted/security/EncryptionData.java
- src/main/java/org/opensearch/repository/encrypted/security/EncryptionDataGenerator.java
- src/main/java/org/opensearch/repository/encrypted/security/EncryptionDataSerializer.java
- src/main/java/org/opensearch/repository/encrypted/security/Encryptor.java
- src/main/java/org/opensearch/repository/encrypted/security/RsaKeysReader.java
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositoryPluginIT.java
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositorySettingsTests.java
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositoryTests.java
- src/test/java/org/opensearch/repository/encrypted/RsaKeyAwareTest.java
- src/test/java/org/opensearch/repository/encrypted/security/CryptoIOTests.java
- src/test/java/org/opensearch/repository/encrypted/security/EncryptionDataSerializerTests.java
- src/test/java/org/opensearch/repository/encrypted/security/RsaKeysReaderTests.java
- src/yamlRestTest/java/org/opensearch/repository/encrypted/EncryptedRepositoryClientYamlTestSuiteIT.java
- bump gradle to 8.3
- return back checktysle
- use BC as a library so no it works just fine with OS 2.9 (tested it together with the sec plugin)
- added spotless eclipse formatter
> Misc changes

- gradle.properties
> Release 2.11.1.0

- build.gradle
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositoryTests.java
> Bump OS to 2.18

- .gitignore
- build.gradle
- src/test/java/org/opensearch/repository/encrypted/EncryptedRepositoryTests.java
> Bump OS to 2.19.1

- .github/workflows/CI.yml
- build.gradle
> Bump OS to 3.0.0-alpha1
